name: PR Tests

on:
  pull_request_target:
    branches:
      - main

jobs:
  run-hidden-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Checkout private tests repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.TESTS_REPO_OWNER }}/${{ secrets.TESTS_REPO_NAME }}
          token: ${{ secrets.TESTS_REPO_TOKEN }}
          path: hidden-tests
      
      - name: Copy test files
        run: |
          echo "Copying test data"
          cp -R hidden-tests/src/test/resources src/test/resources
          echo "Test data copied"
          rm -rf hidden-tests
      
      - name: Run tests
        run: mvn -B test
